console:
	@node-console

test:
	npm test -s

start:
	npm start

{
  "name": "basic-node-project",
  "version": "1.0.0",
  "description": "Минимальный проект с console/test/start",
  "main": "index.js",
  "scripts": {
    "node-console": "node -e \"console.log('Hello from node-console! Now you can run interactive code.'); require('repl').start()\"",
    "test": "npm run test-unit",
    "test-unit": "node test.js",
    "start": "node index.js"
  },
  "keywords": [],
  "author": "",
  "license": "ISC"
}
